---
title: "Project"
author: "Zack Wixom"
output: github_document
---

## Project Workflow

1. Data Story

- Begin with a conceptual story: Where do these data come from? What does the theory say?

- Translate into probability statements (i.e., the likelihood or observational model).

- The resulting model is generative.

2. Bayesian Updating

- Bayesian updating is learning! (See illustration.)

- Every posterior is the prior for the next observation.

- Natural consequence of probability.
The sample size is automatically embodied in the posterior (i.e., no “degrees of freedom”).

3. Evaluate

- Inference is conditioned on the chosen model.

- Use prior predictive checks and posterior predictive checks to evaluate the model.

- Modeling is iterative. You’ll likely need to revise your story.

## Project Organization

There are certain limitations on the size and type of files that can be pushed to GitHub. There are also certain things that shouldn't be accessible by the public (e.g., data we have a license to access). For these reasons, we have folders and files that are pushed to GitHub and those that are not.

### Pushed to GitHub

* `/Code` Each script should do something specific (like tidyverse functions), have a descriptive name, and include number prefixes if they are meant to be run in a certain order (e.g., `01_import_data.R`, `02_clean_data.R`).
* `/Data` While all data live here, only data that are small and can be shared publicly will be pushed.
* `/Figures` Figures live here, including images (saved as PNG files) and data referenced or used for tables, for use in the `README` and report.
* `/Report` The report, without any PDF knits.
* `README` This page, with any other organization details to make it easy to navigate your repository.

### Not Pushed to GitHub

* `/Output` Output from model runs. These files tend to be too large. They are also something each user can create on their own.

