---
title: "Figuring Things Out"
author: "Zack Wixom"
output: github_document
---

## Project Overview

I am still deciding on what I want to do. I have a few ideas of what would be really interesting to do but not sure what type of analysis to do. Partially one of the reasons I am leaning towards one of these types of projects is because it would be a dream to work for a company in these industries so creating a project on relevant data would be beneficial for me as I stand out in applications and can share this. So here are some of my ideas...

#### _Ideas_

- __eSports/Videogame data__
  + Either with _Super Smash Bros_ or _Fornite_ looking at stats of professional players.
  + I know there is data for _Fornite_ that I have found on Kaggle before but mostly it is like players earnings.
  + I would like to use some kind of data from the games themselves, like in _Super Smash_ players are always making tier lists for the best characters but if I could make a tier list based on real data from the game combined with professional player stats to decide which characters are actually the best, etc.
  + It would also be really interesting to look at maybe another game genre that isn't competitive like _Zelda_ franchise. _Breath of the Wild_ is such a large game there has to be data and some kind of analysis that would be interesting.

- __Music data__
  + I did a project using Spotify data recently and it was super interesting and it would be cool to do some kind of analysis looking into a specific genre.
  + I love _lo-fi_ music and I think it is a very unique space where there are a lot of artists but they aren't really looking to get famous, it seems like more of a place for artists to make music for themselves. 
  + The problem is that I don't know if I can find the data for something like this. You can get Spotify for developers and look at your own music playlists but it is very limited, atleast with the R packages and APIs available such as `Rspotify`.
  + Python has an API that seems to gather more data such as stats like tempo, danceability, etc. that have to do with the music themselves.

- __Other__
  + I am also open to other ideas. I think I need to read around these topics to see if there is any gaps in research that I could work on.
  
  

### Data Story for eSports

**Fortnite**

Going off of my eSports idea for the project the data story would be consistently of data that I can get groups out of. There are some stats on professional Fortnite players and recently the game has come out with an _Icon Series_ Skins that are of professional players. 

Right now there are four _icon_ skins out, it would be interesting to be able to build a model that shows what features are going into determining these skins and which players get them or not. 

SO there might be a way to group the data into the type of player (competitive players, YT content creators, etc.)

I need to get data on player statistics and also either find a time series of when the icon series came out or just mutate my own data into it for that. 

**Smash**

As far as getting data for Smash Bros. I do have this website with frame data for every character

[frame data](https://ultimateframedata.com/stats.php#0)

I can't download this but perhaps I can translate it into my own excel file. If I want to use this data I could then also find some player stats on which characters are used the most in tournaments and then join those so that there is a frequency column on how many times they are used in tournaments as well as how many games they win. Frame data to help predict what characters win more often. 

As far as groupings, there are groups of types of characters as Heavy, Med and Light. Perhaps this can be used as well in the data, but there aren't that many charcters that perhaps a futher grouping isn't necessary. 

This can be developed into a tier list that is more accurate than what people usually make from their own opinion. 


